destination: ../doc_outputs/mydoc/writers-pdf
url: "http://127.0.0.1:4012"
baseurl: "/mydoc/writers-pdf"
port: 4012
output: pdf
print_title: Jekyll theme for documentation — writers
print_subtitle: version 4.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true